version: '3'
services:
  mysql:
    image: mysql
    env_file:
      - .env
    ports:
      - "3306:3306" 
    volumes:
      - mysql-data:/var/lib/mysql

  app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - mysql
    env_file:
      - .env

volumes:
  mysql-data:
