services:
  mysql:
    image: mysql
    env_file:
      - ../app/.env
    ports:
      - "3306:3306" 
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - database-network

  app:
    build:
      context: ../app
      dockerfile: Dockerfile
    env_file:
      - ../app/.env
    ports:
      - "3000:3000"
    depends_on:
      - mysql
    networks:
      - backend-network
      - database-network

volumes:
  mysql-data:

networks:
  backend-network:
    driver: bridge
  database-network:
    driver: bridge