services:
  mysql:
    image: mysql
    env_file:
      - ../backend/app/.env
    ports:
      - "3306:3306" 
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - database-network

  app:
    build:
      context: ../backend/app
      dockerfile: Dockerfile
    env_file:
      - ../backend/app/.env
    ports:
      - "3001:3001"
    depends_on:
      - mysql
    networks:
      - backend-network
      - database-network

  web:
    build:
      context: ../frontend/web
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - app
    networks:
      - frontend-network
      - backend-network

volumes:
  mysql-data:

networks:
  frontend-network:
    driver: bridge
  backend-network:
    driver: bridge
  database-network:
    driver: bridge