version: '3'
services:
  mysql:
    image: mysql
    env_file:
      - ../app/.env
    ports:
      - "3306:3306" 
    volumes:
      - mysql-data:/var/lib/mysql

  app:
    build:
      context: ../app
      dockerfile: Dockerfile
    env_file:
      - ../app/.env
    ports:
      - "3000:3000"
    depends_on:
      - mysql

volumes:
  mysql-data:
